import * as fs from "node:fs";
import * as path from "node:path";
import * as readline from "node:readline";
import { VaultError, ConfigError } from "./errors.js";

export interface BootstrapOptions {
  email: string;
  agentName: string;
  apiKey?: string;
  apiBase?: string;
  envPath?: string;
  shroudProvider?: string;
}

export interface BootstrapResult {
  agentId: string;
  vaultId: string | undefined;
  apiKey: string;
  envPath: string;
}

interface TokenExchangeResponse {
  access_token: string;
  expires_in: number;
  agent_id?: string;
  vault_ids?: string[];
}

async function enrollAgent(
  apiBase: string,
  email: string,
  name: string,
): Promise<{ agent_id: string; message: string }> {
  const res = await fetch(`${apiBase}/v1/agents/enroll`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ name, human_email: email }),
  });

  if (!res.ok) {
    const body = (await res.json().catch(() => ({}))) as Record<string, string>;
    throw new VaultError(
      "ENROLL_FAILED",
      body.detail || body.message || `Enrollment failed (HTTP ${res.status})`,
    );
  }

  return res.json() as Promise<{ agent_id: string; message: string }>;
}

async function exchangeToken(
  apiBase: string,
  apiKey: string,
): Promise<TokenExchangeResponse> {
  const res = await fetch(`${apiBase}/v1/auth/agent-token`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ api_key: apiKey }),
  });

  if (!res.ok) {
    const body = (await res.json().catch(() => ({}))) as Record<string, string>;
    throw new VaultError(
      "TOKEN_EXCHANGE_FAILED",
      body.detail || body.message || `Token exchange failed (HTTP ${res.status})`,
    );
  }

  return res.json() as Promise<TokenExchangeResponse>;
}

async function verifyConnection(
  apiBase: string,
  token: string,
): Promise<void> {
  const res = await fetch(`${apiBase}/v1/agents/me`, {
    headers: { Authorization: `Bearer ${token}` },
  });

  if (!res.ok) {
    throw new VaultError(
      "VERIFY_FAILED",
      `Verification failed (HTTP ${res.status}). Is the API key correct?`,
    );
  }
}

function promptLine(query: string): Promise<string> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stderr,
  });
  return new Promise((resolve) => {
    rl.question(query, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

function log(message: string): void {
  process.stderr.write(`${message}\n`);
}

function buildEnvContent(vars: Record<string, string>): string {
  const lines: string[] = [
    "# Generated by 1claw-hermes bootstrap",
    `# ${new Date().toISOString()}`,
    "",
  ];

  for (const [key, value] of Object.entries(vars)) {
    lines.push(`${key}=${value}`);
  }

  lines.push("");
  lines.push("# Optional overrides (uncomment to customize):");
  lines.push("# ONECLAW_MCP_URL=https://mcp.1claw.xyz/mcp");
  lines.push("# SHROUD_URL=https://shroud.1claw.xyz/v1");
  lines.push("# SHROUD_PROVIDER=anthropic");
  lines.push("# HERMES_CONFIG_DIR=~/.hermes");
  lines.push("");

  return lines.join("\n");
}

export async function bootstrap(
  options: BootstrapOptions,
): Promise<BootstrapResult> {
  const apiBase = options.apiBase ?? "https://api.1claw.xyz";
  const envPath = options.envPath ?? path.resolve(
    path.dirname(new URL(import.meta.url).pathname),
    "..",
    ".env",
  );
  const shroudProvider = options.shroudProvider ?? "anthropic";

  log(`Enrolling agent "${options.agentName}" for ${options.email}...`);

  await enrollAgent(apiBase, options.email, options.agentName);
  log(`Enrollment sent! Check ${options.email} for the approval email.`);

  let apiKey = options.apiKey;
  if (!apiKey) {
    if (!process.stdin.isTTY) {
      throw new ConfigError(
        "No API key provided and stdin is not a TTY. " +
        "Pass --api-key or run interactively.",
      );
    }
    log("");
    log("After approving the enrollment, you'll receive an API key (ocv_...).");
    apiKey = await promptLine("Paste your API key: ");
  }

  if (!apiKey.startsWith("ocv_")) {
    throw new ConfigError(
      `Invalid API key format — expected "ocv_" prefix, got "${apiKey.slice(0, 8)}..."`,
    );
  }

  log("Exchanging credentials...");
  const tokenData = await exchangeToken(apiBase, apiKey);

  const agentId = tokenData.agent_id ?? "unknown";
  const vaultId = tokenData.vault_ids?.[0];

  log("Verifying connection...");
  await verifyConnection(apiBase, tokenData.access_token);

  log(`Connected! Agent: ${options.agentName} (${agentId})`);
  if (vaultId) {
    log(`Vault: ${vaultId} (auto-discovered)`);
  } else {
    log("No vault auto-discovered — set ONECLAW_VAULT_ID manually or create a vault at https://1claw.xyz");
  }

  if (fs.existsSync(envPath)) {
    if (process.stdin.isTTY) {
      const overwrite = await promptLine(
        `.env already exists at ${envPath}. Overwrite? [y/N] `,
      );
      if (overwrite.toLowerCase() !== "y") {
        log("Skipped writing .env — configure manually.");
        return { agentId, vaultId, apiKey, envPath };
      }
    } else {
      const backupPath = `${envPath}.bak.${Date.now()}`;
      await fs.promises.copyFile(envPath, backupPath);
      log(`Backed up existing .env to ${backupPath}`);
    }
  }

  const envVars: Record<string, string> = {
    ONECLAW_AGENT_API_KEY: apiKey,
    ONECLAW_API_BASE: apiBase,
  };
  if (vaultId) envVars.ONECLAW_VAULT_ID = vaultId;
  if (shroudProvider !== "anthropic") envVars.SHROUD_PROVIDER = shroudProvider;

  const content = buildEnvContent(envVars);
  const tmpPath = `${envPath}.tmp`;
  await fs.promises.writeFile(tmpPath, content, "utf-8");
  await fs.promises.rename(tmpPath, envPath);
  log(`Wrote ${envPath} — you're ready to go.`);

  return { agentId, vaultId, apiKey, envPath };
}
